language: ruby
rvm:
  - 2.5.1
script:
  - bin/rake db:migrate RAILS_ENV=test
  - bin/rake
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
test:
  adapter: postgresql
  database: travis_ci_test
