source 'https://rubygems.org'
ruby '2.5.1'

gem 'capybara'
gem 'data_mapper'
gem 'database_cleaner'
gem 'dm-postgres-adapter'
gem 'pg'
gem 'pry'
gem 'rspec'
gem 'rubocop'
gem 'simplecov'
gem 'sinatra'
gem 'timecop'
